vich_uploader:
    db_driver: orm
    mappings:
        article_image:
            uri_prefix: /assets/images
            upload_destination: '%kernel.project_dir%/public/assets/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # Suppression des options non reconnues
            # inject_on_update: false
            # inject_on_create: true
