<?php

namespace ContainerUbcKMTP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NHC1sThService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nHC1sTh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nHC1sTh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\IndexController::index()', 'getIndexControllerindexService', true],
            'App\\Controller\\ProduitsController::index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ProduitsController::index()', 'getProduitsControllerindexService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\IndexController::index()', 'getIndexControllerindexService', true],
            'App\\Controller\\ProduitsController:index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ProduitsController::index()', 'getProduitsControllerindexService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\ProduitsController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\ProduitsController:index' => '?',
        ]);
    }
}
