<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUbcKMTP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUbcKMTP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUbcKMTP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUbcKMTP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUbcKMTP\App_KernelDevDebugContainer([
    'container.build_hash' => 'UbcKMTP',
    'container.build_id' => 'd505b351',
    'container.build_time' => 1730070004,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUbcKMTP');
