<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRN2cZG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRN2cZG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRN2cZG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRN2cZG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSRN2cZG\App_KernelDevDebugContainer([
    'container.build_hash' => 'SRN2cZG',
    'container.build_id' => '971b2388',
    'container.build_time' => 1728916265,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRN2cZG');
